-- AlterTable
ALTER TABLE `User` ADD COLUMN `apartment` VARCHAR(191) NULL,
    ADD COLUMN `city` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `companyName` VARCHAR(191) NULL,
    ADD COLUMN `country` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `pinCode` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `state` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `streetAddress` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `address` VARCHAR(191) NULL;
