name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ./psycortex
            git pull origin main
            
            # Backend deployment
            cd backend
            npm i
            pm2 restart psycortex
            
            # Frontend deployment
            cd ../frontend
            npm i
            npm run build
            
            # Restart nginx
            sudo systemctl restart nginx